name: Unit Tests

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Set up JDK
        uses: actions/setup-java@v3.10.0
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Run project gradle
        run: ./gradlew testDebugUnitTest
        
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.7
        with:
          # Artifact name
          name: github-pages
          # Path of the directory containing the static assets.
          path: /home/runner/work/2023Voltage/2023Voltage/TeamCode/build/reports/tests/testDebugUnitTest
          # Duration after which artifact will expire in days.
          retention-days: 7
  deploy:
    
    needs: build
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write
      
    steps:
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v1.2.4
